export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';

